import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopAppBar from "@/app/navigation/top-app-bar";
import NavigationDrawer from "./navigation/nav-drawer";
import { Box, CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppRouterCacheProvider>
					<CssBaseline />
					<Box sx={{ display: "flex" }}>
						<TopAppBar></TopAppBar>
						<NavigationDrawer></NavigationDrawer>
						{children}
					</Box>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
